[versions]

[libraries]
gson = "com.google.code.gson:gson:2.9.1"
jsr250 = "javax.annotation:jsr250-api:1.0"
junit4 = "junit:junit:4.13.2"

[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "0.3.0" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.26.1" }
publishOnCentral = { id = "org.danilopianini.publish-on-central", version = "2.0.8" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "0.4.12" }
taskTree = { id = "com.dorongold.task-tree", version = "2.1.0" }
