[versions]

[libraries]
gson = "com.google.code.gson:gson:2.10.1"
jsr250 = "javax.annotation:jsr250-api:1.0"
junit4 = "junit:junit:4.13.2"

[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "3.1.2" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.60.1" }
publishOnCentral = { id = "org.danilopianini.publish-on-central", version = "5.0.23" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "0.5.8" }
taskTree = { id = "com.dorongold.task-tree", version = "2.1.1" }
