[versions]

[libraries]
gson = "com.google.code.gson:gson:2.11.0"
jsr250 = "javax.annotation:jsr250-api:1.0"
junit4 = "junit:junit:4.13.2"

[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "3.1.5" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.62.0" }
publishOnCentral = { id = "org.danilopianini.publish-on-central", version = "5.1.1" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "0.5.8" }
taskTree = { id = "com.dorongold.task-tree", version = "3.0.0" }
