[versions]

[libraries]
gson = "com.google.code.gson:gson:2.12.0"
jsr250 = "javax.annotation:jsr250-api:1.0"
junit4 = "junit:junit:4.13.2"

[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "4.0.2" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.78.0" }
publishOnCentral = { id = "org.danilopianini.publish-on-central", version = "8.0.2" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "3.2.2" }
taskTree = { id = "com.dorongold.task-tree", version = "4.0.0" }
