name: CI
on:
  push:
    tags: '*'
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'renovate.json'
      - '.gitignore'
      - README.md
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ windows, macos, ubuntu ]
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 20
    steps:
      - name: Install Jabba on Linux
        if: matrix.os == 'ubuntu'
        shell: bash
        run: |
          curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
          sudo ln -s "$HOME/.jabba/bin/jabba" /usr/bin/jabba
          jabba ls-remote
      - name: Install JDK 6 on Linux
        if: matrix.os == 'ubuntu'
        shell: bash
        run: |
          ls -ahl "$HOME/.jabba/bin/"
          ls -ahl /usr/bin/jabba
          jabba install zulu@1.6.119
      - name: Install JDK 7 on Linux
        if: matrix.os == 'ubuntu'
        shell: bash
        run: jabba install zulu@1.7.292
      - name: Checkout
        uses: danysk/action-checkout@0.2.1
      - name: Get branch name
        id: branch
        uses: tj-actions/branch-names@v5
      - uses: DanySK/build-check-deploy-gradle-action@1.1.2
        with:
          build-command: |
            ./gradlew -q javaToolchains
            ./gradlew assemble --parallel
          deploy-command: |
            ./gradlew signJavaMavenPublication --parallel
            ./gradlew closeJavaMavenOnMavenCentralNexus
          should-run-codecov: ${{ contains('Linux', runner.os) }}
          should-deploy: >-
            ${{
              contains('Linux', runner.os)
              && contains(github.repository, 'DanySK/gson-extras')
              && contains('push workflow_dispatch', github.event_name)
            }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
  Release:
    needs:
      - build
    runs-on: ubuntu-latest
    if: >-
      contains('push workflow_dispatch', github.event_name)
      && contains(github.repository, 'DanySK/gson-extras')
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
      - uses: DanySK/build-check-deploy-gradle-action@1.1.2
        with:
          build-command: true
          check-command: true
          deploy-command: |
            npm install
            npx semantic-release
          should-run-codecov: false
          should-deploy: true
          should-validate-wrapper: false
          github-token: ${{ secrets.DEPLOYMENT_TOKEN }}
          maven-central-password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing-key: ${{ secrets.SIGNING_KEY }}
          signing-password: ${{ secrets.SIGNING_PASSWORD }}
